import type { Metadata } from 'next'
import '../app/ui/globals.css'
import { Roboto_Slab } from 'next/font/google'
import { roboto } from './ui/fonts'

const robotoSlab = Roboto_Slab({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Utopía',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es">
      <body className={`${roboto.className} bg-gray-100 text-gray-900 antialiased`}>{children}</body>
    </html>
  )
}
